### ISSUE TITLE
Not working with PureLayout

### ISSUE THREAD

**Issue by ppamorim** [bigfish24/ABFRealmMapView#5] opened 2015-10-14 16:49 UTC
I tried to use this library with PureLayout (auto layout ifself). But it have some problems, I think that`s is a problem with Swift 2 too.

Source code of the sample of the error, you can fork/download it and try yourself: https://github.com/ppamorim/Fun-with-Swift/blob/master/Fun%20With%20Swift/ABFRealmMapView.swift

![captura de tela 2015-10-14 as 13 47 08](https://cloud.githubusercontent.com/assets/5521682/10490969/4a89c13c-727a-11e5-9dbd-d328091b2e3a.png)

**Comment by bigfish24** [comment] 2015-10-14 16:55
The issue is that entityName, latitudeKeyPath, or longitudeKeyPath is nil.

You need to set these to match the Realm object you are displaying.

**Comment by bigfish24** [comment] 2015-10-14 16:56
I should add better assertions to make this obvious though...

**Comment by ppamorim** [comment] 2015-10-14 16:56
But I`m using the ABFRestaurantScoresPath too.

**Comment by ppamorim** [comment] 2015-10-14 17:00
I tried to create a empty map and has the sample problem (yes, I removed the logic code of the pin insertion, only maintain the load of the map).

**Comment by bigfish24** [comment] 2015-10-14 17:01
No that's just the path to the realm file. You have to the properties on what the map view will fetch and display from the realm file.

In the swift example these are set in the main storyboard:

<userDefinedRuntimeAttribute type="string" keyPath="entityName" value="ABFRestaurantObject"/>
                                    <userDefinedRuntimeAttribute type="string" keyPath="latitudeKeyPath" value="latitude"/>
                                    <userDefinedRuntimeAttribute type="string" keyPath="longitudeKeyPath" value="longitude"/>
                                    <userDefinedRuntimeAttribute type="string" keyPath="titleKeyPath" value="name"/>
                                    <userDefinedRuntimeAttribute type="string" keyPath="subtitleKeyPath" value="phoneNumber"/>

**Comment by ppamorim** [comment] 2015-10-14 17:01
```swift
import PureLayout
import RealmMapView
import RealmSwift
import RealmSwiftSFRestaurantData

class ABFRealmMapView : UIViewController {
  
  var didUpdateViews = false
  
  var realmMapView : RealmMapView = {
    let realmMapView = RealmMapView.newAutoLayoutView()
    realmMapView.mapType = .Standard
    return realmMapView
    }()
  
  override func loadView() {
    super.loadView()
    self.view.addSubview(realmMapView)
    self.view.setNeedsUpdateConstraints()
  }
  
  override func updateViewConstraints() {
    if(!didUpdateViews) {
      realmMapView.autoMatchDimension(.Width, toDimension: .Width, ofView: self.view)
      realmMapView.autoMatchDimension(.Height, toDimension: .Height, ofView: self.view)
      didUpdateViews = true
    }
    super.updateViewConstraints()
  }
  
}
```

**Comment by ppamorim** [comment] 2015-10-14 17:02
I don`t use Storyboard because my layout is too complex to use it. We need to support the both features.

**Comment by bigfish24** [comment] 2015-10-14 17:04
It supports both, you have to set the properties in the map view. You are not doing that in your code. My point was the example app simply chooses to do that in the storyboard and thus I assume you didn't notice this.

**Comment by bigfish24** [comment] 2015-10-14 17:04
Check out the tutorial in the README

**Comment by ppamorim** [comment] 2015-10-14 17:06
It`s possible to config by code?

**Comment by bigfish24** [comment] 2015-10-14 17:09
Yes, the storyboard simply allows you to do that through the GUI and it sets the properties on the map view at run time for you. Instead you can simply set it anytime before you first calm refresh.

**Comment by ppamorim** [comment] 2015-10-14 17:18
Well done, I can understand your point. this worked fine:

```swift
realmMapView.entityName = "ABFRestaurantObject"
    realmMapView.latitudeKeyPath = "latitude"
    realmMapView.longitudeKeyPath = "longitude"
    realmMapView.titleKeyPath = "name"
    realmMapView.subtitleKeyPath = "sub"
```

But this is really necessary? Would we create a fluent API to do this configuration and avoid this problem (that`s would be hard to handle if you are a beginner) with asserts and something more?

**Comment by bigfish24** [comment] 2015-10-14 17:35
Well it is necessary in the sense that in some interface this data needs to be defined in the map view. I started with this because it allows you to define in Interface Builder (via `@IBInspectable`), or through code... but I agree it could be improved.

Not sure a fluent interface is necessary, but a custom initialization method that takes these parameters would definitely clean it up.

Want to take a stab with implementing through a PR?

**Comment by ppamorim** [comment] 2015-10-14 17:36
+1
I`ll do it soon.

**Comment by ppamorim** [comment] 2015-10-14 18:32
@bigfish24 Can you look for this another problem?

https://github.com/PureLayout/PureLayout/issues/102

I don`t think that`s a problem with your library... But you can help.

**Comment by bigfish24** [comment] 2015-10-14 21:19
@ppamorim I am not familiar with this other library, but looking at the video, it definitely seems like that is a PureLayout issue. Sorry but hopefully the maintainer their can help you.

**Comment by bigfish24** [comment] 2015-10-14 21:35
I am going to close this for now since the main issue was solved.

**Closed by bigfish24** 2015-10-14 21:35 UTC

**Comment by ppamorim** [comment] 2015-10-15 12:45
@bigfish24 The click issue is solved, it needs to set the view to center with ```realmMapView.autoCenterInSuperview()```
