### ISSUE TITLE
Is it possible to change the the way the annotations look on the map?

### ISSUE THREAD

**Issue by eyaldar** [bigfish24/ABFRealmMapView#12] opened 2016-01-02 11:51 UTC
For example, extending your restaurant in way that a cluster with 1 item will display an image of the restaurant's logo or photograph on the map instead of the red circle with "1" mark or alternatively change the cluster's pin altogether?

**Comment by bigfish24** [comment] 2016-01-15 17:31
You can make your own subclass of `MKAnnotationView`. The library comes with `ABFClusterAnnotationView` as the default, but you could definitely alter this or create a new one and then override the delegate: `mapView:viewForAnnotation:` to return this view so that the default doesn't show.

**Comment by Chris59160** [comment] 2016-01-21 08:33
I have actually implemented it myself since I needed it. As bigfish24 says, it's quite easy...however I found a bug in ios 7.
On ios 7, if you give an image to an annotation in order to display a custom pin, on ios 7, if the pin was a part of a cluster, it will draw a cluster, without label using your image frame for the frame. On ios 8, it works as intended...Haven't figured out the issue yet.

So if you need any help, I can provide you with the set of classes customized. Issue is, if bigfish24 updates the plugin...you need to do a diff to see what's new unless you're happy with your current files.

**Comment by eyaldar** [comment] 2016-01-21 12:30
That would be great Chris59160, thank you both for your help!

**Comment by Chris59160** [comment] 2016-01-21 15:54
Luckily for you, I have edited it as well to be able to show more than 1 pin for the same location (i.e if 2 restaurants or whatever have exactly the same coordinates, it will give them an offset and position them on a circle whose center is the original location :-). Let me tidy that a bit and I will send it to you

**Comment by Chris59160** [comment] 2016-01-22 10:20
@eyaldar , Can you give me an address I can send you the file to ?

**Comment by eyaldar** [comment] 2016-01-22 11:49
Sure, here: Eyaldar@gmail.com

**Comment by bigfish24** [comment] 2016-01-22 19:53
@Chris59160 is your custom annotation view a subclass of `ABFClusterAnnotationView`?

Also, thanks so much for being supportive and sharing your solution with @eyaldar!

**Comment by Chris59160** [comment] 2016-01-24 22:19
I will package them tomorrow, my weekend was a bit crazy so no time. I need to remove stuff from them (Company's code, not mine to own), and if you have any question, feel free to email me back :-)

**Comment by Chris59160** [comment] 2016-01-27 17:44
Just sent the package Eyaldar. Sorry it took so long, was super super busy at work.

It will probably not be clear what I have edited. Since I have my own database, you can't just copy paste, you will need to edit some files to have your own RLMObjects showing up and not crashing.

Need any help to nagivate through my files and get what I changed, feel free to contact me :-)

**Comment by eyaldar** [comment] 2016-01-27 17:50
I'll review the code and try to understand it, Thanks again for all your help @Chris59160 !

**Comment by bigfish24** [comment] 2016-05-19 21:01
Closing this for now

**Closed by bigfish24** 2016-05-19 21:01 UTC
Labels: help wanted

**Comment by kristiyandobrev** [comment] 2017-01-26 12:14
@Chris59160 is it possible to share the solution here ?

**Comment by Chris59160** [comment] 2017-01-26 12:33
@kristiyandobrev I can send you the code if you want ? I haven't updated it at all, and have been a bit lazy on copying/pasting. I don't have the time to really make it nice haha.

Let me know the email you wish me to use and I'll send it to you

**Comment by kristiyandobrev** [comment] 2017-01-26 12:34
Sure : kristiyandobrev@protonmail.com
